### ISSUE TITLE
RES and CONV PP related issues (dp v0.3)

### ISSUE THREAD

**Issue by nesnoj** [openego/data_processing#181]
This issue is to collect RES and CONV PP-related bugs we found recently. Please tick here if resolved and close related issue.

- [x] Fix changing ids of conv generators in different scenarios #175 @wolfbunke   v0.3.0
- [x] RES generators in the sea (not wind offshore) #176 @wolfbunke  v0.3.1
- [x] Decommissioning of conv. PP #178 @wolfbunke  v0.3.0
- [x] Bug in v_level of generators #179 @IlkaCu v0.3.1
- [x] Move pre-data_processing of RES and Conv Power plants to DP (bug in version no.) #180 @wolfbunke @ulfmueller @IlkaCu v0.3.1
- [x] RES PP with capacity=0 #182 @wolfbunke v0.3.0
- [x] Missing subst_id in commissioned RES #184 @wolfbunke v0.3.0
- [x] Validate new tables - Re-check if above bugs are resolved @wolfbunke v0.3.0 & v0.3.1
- [x] Check and update supply tables #166 @wolfbunke v0.3.0
- [x] Documentation: The current method how tables/mviews are created, which data is used, filtered etc. should be documented somewhere...at least, the BPMN should be updated and it should be documented how the scenarios are created (I already had a bunch of people who wanted to use the datasets from OEP asking amny questions I could not answer ).. @wolfbunke v0.3.0
_Logic: SQ = SQ, SQ +NEP = NEP, SQ+NEP +eGO 100 = eGo 100_

If I forgot about something, please amend list.

**Comment by nesnoj** [comment]
One more question @IlkaCu @wolfbunke:
Does the v_level change in future scenarios if the increasing capacity of a PP exceeds the threshold of the next voltage level (according to [our table](http://oep.iks.cs.ovgu.de/redmine/projects/open_ego/wiki/Methoden_Zuordnung_von_Erzeugern_und_Verbrauchern_zu_Spannungsebenen_und_Netzknoten))?

**Comment by wolfbunke** [comment]
Thx, @nesnoj, I updated the version numbering and continue with this list on the next days.

**Comment by nesnoj** [comment]
Thx!
Uh, now it seems I do not have sufficient privileges to access the mviews - please update the ownership to `oeuser`!

**Comment by nesnoj** [comment]
> Does the v_level change in future scenarios if the increasing capacity of a PP exceeds the threshold of the next voltage level (according to our table)?

I had a chat with @wolfbunke:
- RES: Wind and PV are extended by using new PP only -> **no v_level change!**
- RES: Water and Biomass are extended by updating capacities as well as new PP -> **v_level changes may occur**
- CONV: Both, new PP as well as updated capacities -> **v_level changes may occur**

I hope I got this right, @wolfbunke ?

**Comment by wolfbunke** [comment]
yes, from my part of scripts. I am not sure if @IlkaCu is using a script in dp in order to change the v_level by our size assumption later on?

**Comment by IlkaCu** [comment]
Sorry for not answering earlier. 
In the [code](https://github.com/openego/data_processing/blob/release/v0.3/preprocessing/sql_snippets/ego_pre_voltage_level.sql#L118-L126) we make sure that all conventional power plants keep the same voltage level in all scenarios regardless of whether their capacity changes or not.

**Comment by nesnoj** [comment]
ok, cheers

**Comment by nesnoj** [comment]
Almost all v0.3-related issues seem to be resolved.
If you @wolfbunke are sure that the bugs which are marked as done are fixed, go ahead..

What is the current plan for the docs? By now, I've no idea how an external user is supposed to understand the relations of the supply tables (except of the papers published but they lack of details)..

**Comment by wolfbunke** [comment]
This is a good point. I took a look if we can maybe use Docstrings like in Python with sphinx docs but I didn't find a good solution for sql scripts. Maybe we just write md or rST Filies plus a update of bpmn and implement them in our read the docs?

**Comment by nesnoj** [comment]
@wolfbunke @IlkaCu 
In the current dataset the columns `rea_geom_new` and `mvlv_subst_id` are **EMPTY**.
Are you currently running scripts on the supply tables?

**Comment by wolfbunke** [comment]
Hey @nesnoj , it looks like the rea script doesn't run full. I will start the missing parts in the evening at the moment I am at the train back home.

**Comment by nesnoj** [comment]
Ok, please gimme a *trööt* as soon as it is done..

**Comment by wolfbunke** [comment]
The script is in the m5 section of the rea scripts and runs since 20 hours. I let it run over night at office and hope it's tomorrow done.

**Comment by wolfbunke** [comment]
Ok, trööt ... I hope there is not another DP Script missing.

**Comment by nesnoj** [comment]
Did you update the MVIEWS as well?

**Comment by wolfbunke** [comment]
no, it is running now. Thanks for you!

**Comment by wolfbunke** [comment]
MViews are refreshed with following code: https://github.com/openego/data_processing/blob/release/v0.3-refresh-mviews/dataprocessing/sql_snippets/ego_dp_refresh_mviews.sql
It is four times faster as before.

**Comment by wolfbunke** [comment]
MView Documentation as bpmn can be found here: https://github.com/openego/data_processing/blob/release/v0.3/bpmn/eGo_bpmn_pp_mviews.graphml

**Comment by nesnoj** [comment]
:+1: Thank you @wolfbunke

**Comment by wolfbunke** [comment]
can we close this issue?
