### ISSUE TITLE
change weather time series tabels and Process

### ISSUE THREAD

**Issue by wolfbunke** [openego/data_processing#206]
@MarlonSchlemminger is working on a simple way to implement the weather data into the Dataprocessing. As an preprocessing script a new table will be created without any direct relation to the substation id's. The time series will be normalized to a plant size of 1 kW for wind on- and offshore and solar with the option of several weather year or weather data sources. 

**ToDo's:**
- [ ]  create new table in model_draft and supply (versioned)
- [ ]  import data and place script into /preprocessing/python_scripts/
- [ ] change ego_dp_powerflow_timeseries_generator.sql in order to use new time series, use w_id for the data relation and climate.cosmoclmgrid

**Comment by MarlonSchlemminger** [comment]
I created a pull request for this and I think the implementation was successfull. P_sets in the table generator_pq_sets remain untouched, which means they are still calculated by renpassgis. The new feature is that p_max_pu is no longer p_set/p_nom, but is now calculated directly by simplefeedin without using renpassgis. P_max_pu is assigned by w_id which means that the results are much more specific and accurate compared to p_set. I evaluated the results by comparing p_set and p_max_pu for each generator and the new results for p_max_pu seem resonable.  The attached file "Produktionssummen.txt" shows yearly productions for each scenario from solar and wind. "renpass" is the production given by p_set from renpass and "simplefeedin" is the new production given by p_max_pu from simplefeedin. The production from simplefeedin looks realistic and is similar to the production from renpass. On top of that, both production curves follow similar patterns (peaks and lows at the same times), indicating that the process worked correctly.
@ulfmueller @IlkaCu 
This resvoled issue #215 as well.
![sq_wind](https://user-images.githubusercontent.com/22960010/36383503-9c2ee488-158c-11e8-8604-a1b6e30555ba.png)
[Produktionssummen.txt](https://github.com/openego/data_processing/files/1737171/Produktionssummen.txt)
